package gammaBetaMc.resources;

import java.util.ListResourceBundle;

/**
 * The resource bundle for BoxApp class. <br>
 * 
 * @author Dan Fulea, 27 Jun. 2011
 * 
 */
public class BoxAppResources extends ListResourceBundle {
	/**
	 * Returns the array of strings in the resource bundle.
	 * 
	 * @return the resources.
	 */
	public Object[][] getContents() {
		return CONTENTS;
	}

	/** The resources to be localised. */
	private static final Object[][] CONTENTS = {
			// ####################################

			{ "form.icon.url", "/danfulea/resources/personal.png"},//"/jdf/resources/duke.png" },
			{ "icon.url", "/danfulea/resources/personal.png"},//"/jdf/resources/globe.gif" },
			{ "simTa.toolTip", "Select text and then hold CNTRL+C to copy!" },
			
			{ "text.simulation.stop", "Interrupred by user!" },
			{ "status.wait", "Waiting for your action!" },
			{ "status.computing", "Computing..." },
			{ "status.done", "All done! " },
			{ "status.error", "Unexpected error!" },
			{ "status.save", "Saved: " },
			{ "status.load", "Loaded: " },
			//{ "data.load", "Data" },
			// about frame...
			{ "about.title", "About..." },
			{ "about.version.label", "Version" },
			{ "main.startsimB", "Run" },
			{ "main.startsimB.mnemonic", new Character('R') },
			{ "main.stopsimB", "Kill" },
			{ "main.stopsimB.mnemonic", new Character('K') },
			{ "rezultat", "" },
			{ "source.border", "Source settings" },
			{ "detector.border", "Detector settings" },
			{ "main.saveSB", "Save source..." },
			{ "main.saveSB.mnemonic", new Character('v') },
			{ "main.saveDB", "Save detector..." },
			{ "main.saveDB.mnemonic", new Character('d') },
			
			{ "pdf.metadata.title", "GES_MC BoxApp PDF" },
			{ "pdf.metadata.subject", "MC-simulation results" },
			{ "pdf.metadata.keywords", "GES_MC BoxApp, PDF" },
			{ "pdf.metadata.author", "GES_MC BoxApp" },
			
			{ "pdf.metadata.title1", "GES_MC G_App PDF" },
			{ "pdf.metadata.subject1", "MC-simulation results" },
			{ "pdf.metadata.keywords1", "GES_MC G_App, PDF" },
			{ "pdf.metadata.author1", "GES_MC G_App" },
			
			{ "pdf.content.title", "GES_MC BoxApp Simulation Report" },
			{ "pdf.content.title1", "GES_MC G_App Simulation Report" },
			{ "pdf.content.subtitle", "Report generated by: " },
			{ "pdf.page", "Page " }, { "pdf.header", "GES_MC BoxApp output" },
			{ "pdf.header1", "GES_MC G_App output" },
			{ "file.extension", "pdf" }, { "file.description", "PDF file" },
			{ "dialog.overwrite.title", "Overwriting..." },
			{ "dialog.overwrite.message", "Are you sure?" },
			{ "dialog.overwrite.buttons", new Object[] { "Yes", "No" } },
			
			{ "main.loadSB", "Load source..." },
			{ "main.loadSB.mnemonic", new Character('L') },
			{ "main.loadDB", "Load detector..." },
			{ "main.loadDB.mnemonic", new Character('o') },
			{ "dettype.label", "Type: " },
			{ "sourcetype.label", "Geometry: " },
			{ "sourceeq.label", "Equivalent composition: " },
			{ "asource.label", "External diameter (cm): " },
			{ "bsource.label", "Internal diameter (cm): " },
			{ "hsource.label", "Total height (cm): " },
			{ "asourceup.label", "Upper height, above detector (cm): " },
			{ "adet.label", "Effective diameter (cm): " },
			{ "hdet.label", "Effective height (cm): " },
			{ "adetTot.label", "Total diameter (cm): " },
			{ "hdetTot.label", "Total height(cm): " },
			{ "hdetUp.label", "Upper inactive volume height (cm): " },
			{ "src.load", "src" },
			{ "src.load.description", "Source file" },
			{ "det.load", "det" },
			{ "det.load.description", "Detector file" },
			{ "data.load", "Data" },
			{ "main.atenuareCh", "Attenuation in source volume" },

			{
					"main.nPhotonsCb",
					new String[] { "10000", "20000", "40000", "60000", "80000",
							"100000", "300000", "500000" } },
			{ "main.detTypeCb", new String[] { "NaI", "Ge" } },
			{ "main.sourceTypeCb",
					new String[] { "Point source", "BOX geometry" } },// geometrie
			{ "main.sourceEqCb",
					new String[] { "H2O", "NaCl", "soil", "concrete" } },
			{ "main.adetTf", "6.3" },
			{ "main.hdetTf", "6.3" },
			{ "main.energyTf", "0.662" },
			// {"main.energyTf.toolTip", "Total energy in MeV!"},
			{ "main.asourceTf", "7.5" },
			{ "main.hsourceTf", "3.4" },
			{ "main.bsourceTf", "0" },
			{
					"main.bsourceTf.toolTip",
					"< source external diamter and > total detector diameter. Marinelli geometry only!" },
			{ "main.hsourceupTf", "0" },
			{ "main.hsourceupTf.toolTip",
					"< total source height. Marinelli geometry only!" },
			{ "main.hdetTotTf", "7.3" },
			{ "main.hdetTotTf.toolTip", "Total height of detector house." },
			{ "main.adetTotTf", "7.3" },
			{ "main.adetTotTf.toolTip", "Total diameter of detector house." },
			{ "main.hUpTf", "0.9" },
			{ "main.hUpTf.toolTip", "Height of upper inactive volume." },
			{ "photon.label", "Number of histories: " },
			{ "en.label", "Incident kinetic energy (MeV): " },
			// menu labels...
			{ "menu.file", "File" },
			{ "menu.file.mnemonic", new Character('F') },

			{ "menu.file.exit", "Close" },
			{ "menu.file.exit.mnemonic", new Character('C') },

			{ "menu.help", "Help" },
			{ "menu.help.mnemonic", new Character('H') },

			{ "menu.help.about", "About..." },
			{ "menu.help.about.mnemonic", new Character('A') },

			// dialog messages...
			{ "dialog.exit.title", "Confirm exit ..." },
			{ "dialog.exit.message", "Are you sure ?" },
			{ "dialog.exit.buttons", new Object[] { "Yes", "No" } },
			{ "dialog.OkCancel.buttons", new Object[] { "Ok", "Cancel" } },
			{ "dialog.filechooser.title", "Save" },
			{ "dialog.filechooser.approveButton", "Save" },
			{ "dialog.filechooser.approveButton.mnemonic", new Character('S') },
			// ##############################################3
			// ---------------------------------------------------------
			{ "egsRb.name", "EGS" },
			{ "egsRb.toolTip", "Recomandat pentru orice energie!" },
			{ "clasicRb.name", "Clasic" },
			{ "clasicRb.toolTip", "" },// "Recomandat pentru energii foarte joase (X-ray) <~0.200 MeV!!!"},
			{ "kahnRb.name", "Kahn" },
			{ "kahnRb.toolTip", "" },// "Recomandat pentru energii joase <~1.000 MeV! Algoritm alternativ pentru EGS sau clasic"},
			{ "wielopolskiRb.name", "Wielopolski" },
			{ "wielopolskiRb.toolTip", "" },// "Nerecomandat! A se utiliza doar ca studiu de comparare!!"},
			{ "kn.border", "Selectare algoritm - Klein_Nishina:" },
			// --------------------------------------------------------
			{ "testB.name", "Test algoritmi" },
			{ "testB.mnemonic", new Character('T') },
			{ "testB.toolTip",
					"Testeaza distributia unghiurilor polare generate de algoritmi" },

			{ "test.energie", " Energie (MeV): " },
			{ "test.photons", " Numar fotoni generati: " },
			{ "test.015", " Probabilitate (%) generare unghiuri 0-15 grade: " },
			{ "test.1530", " Probabilitate (%) generare unghiuri 15-30 grade: " },
			{ "test.3045", " Probabilitate (%) generare unghiuri 30-45 grade: " },
			{ "test.4560", " Probabilitate (%) generare unghiuri 45-60 grade: " },
			{ "test.6075", " Probabilitate (%) generare unghiuri 60-75 grade: " },
			{ "test.7590", " Probabilitate (%) generare unghiuri 75-90 grade: " },
			{ "test.90105",
					" Probabilitate (%) generare unghiuri 90-105 grade: " },
			{ "test.105120",
					" Probabilitate (%) generare unghiuri 105-120 grade: " },
			{ "test.120135",
					" Probabilitate (%) generare unghiuri 120-135 grade: " },
			{ "test.135150",
					" Probabilitate (%) generare unghiuri 135-150 grade: " },
			{ "test.150165",
					" Probabilitate (%) generare unghiuri 150-165 grade: " },
			{ "test.165180",
					" Probabilitate (%) generare unghiuri 165-180 grade: " },
			// ---------------------------------------------------------
			{ "main.calceffB", "Calculeaza" },
			{ "main.calceffB.mnemonic", new Character('C') },
			{ "main.calcactivB", "Calculeaza" },
			{ "main.calcactivB.mnemonic", new Character('l') },

			{ "mc.border", "Simulare Monte Carlo: " },
			{ "eff.border", "Eficienta: " },
			{ "activ.border", "Activitate: " },
			{
					"main.winCb",
					new String[] { "Al", "Al2O3", "Au", "Be", "Fe", "Ge",
							"MgO", "NaI", "Si" } },
			{ "main.win1Tf", "0.05" },
			{ "main.win2Tf", "0.0" },
			{ "main.win3Tf", "0.0" },
			{ "main.win4Tf", "0.0" },
			{ "win1.label", "Fereastra 1:  " },
			{ "win2.label", "Fereastra 2:  " },
			{ "win3.label", "Fereastra 3:  " },
			{ "win4.label", "Fereastra 4:  " },
			{ "material.label", "Material  " },
			{ "thickness.label", "Grosime (cm)  " },

			// {"net.label","Arie neta pic absortie totala (imp/s): "},
			{ "net.label", "Arie neta pic abs.tot.(imp/s): " },
			{ "err.label", "Eroare: " },
			{ "err.pm.label", " +/- " },
			// {"yield.label","Probabilitate emisie pe pic (%): "},
			{ "yield.label", "Probab. emisie pe pic (%): " },
			{ "activ.label", "Activitate (Bq): " },
			{ "eff.label", "Eficienta (%): " },

			{ "main.PleaseWait.label", "Simulare in progres!" },
			{ "ds.timeelapsed", "Durata simularii:   " },
			{ "ds.photon.total",
					"Numarul total de fotoni care intra in detector= " },
			{ "ds.photon.photo",
					"Ponderea evenimenelor legate de absortia fotoelectrica (%)= " },
			{ "ds.photon.pair",
					"Ponderea evenimentelor legate de formarea de perechi (%)= " },
			{ "ds.effind", "Eficienta (%) la rularea: " },
			{ "ds.efffinal", "Eficienta (%) finala: " },

			{ "dialog.double.title", "Eroare..." },
			{ "dialog.double.message", "Introduceti numere reale!" },
			{ "dialog.pos.title", "Eroare..." },
			{ "dialog.pos.message", "Introduceti numere reale pozitive!" },
			{ "dialog.energy.title", "Eroare energie..." },
			{ "dialog.energy.message",
					"Selectati o energie in intervalul [0 - 3.0] MeV!!" },
			{ "dialog.activ.title", "Eroare...." },
			{ "dialog.activ.message",
					"Rulati intai simularea eficientei de detectie!" },
			{ "dialog.marinelli1.title", "Eroare...." },
			{
					"dialog.marinelli1.message",
					"Diametrul interior trebuie sa fie mai mic ca diametrul exterior dar mai mare decat diametrul detectorului!" },
			{ "dialog.marinelli2.title", "Eroare...." },
			{
					"dialog.marinelli2.message",
					"Inaltimea portiunii superioare trebuie sa fie mai mica decat inaltimea totala!" },
			{ "dialog.tot.title", "Eroare..." },
			{ "dialog.tot.message",
					"Dimensiunile totale trebuie sa fie mai mari ca cele efective!" },
			{ "dialog.up.title", "Eroare..." },
			{
					"dialog.up.message",
					"Inaltimea volumului inactiv superior trebuie sa fie mai mica decat diferenta dintre inaltimea totala si cea efectiva!" },
			{ "dialog.thk.title", "Eroare..." },
			{
					"dialog.thk.message",
					"Suma grosimilor ferestrelor trebuie sa fie mai mica decat inaltimea volumului inactiv superior!" },

	};

}
